"""Emit DDL for a schema of sanitised views — the agent's only view of the data.

Withholding sensitive columns from the prompt and rejecting queries that name
them are application-level controls: they hold only as long as the patterns in
sql/guards.py have no gaps, and neither of them stops `SELECT *`. A view that
simply does not contain the column is the control that does not depend on
getting a regex right.

This script only PRINTS the DDL. Review it, then run it yourself (Supabase:
SQL Editor). Everything is CREATE OR REPLACE, so re-run it after a schema
change and apply the output again.

    python scripts/generate_safe_views.py                  # to stdout
    python scripts/generate_safe_views.py -o safe_views.sql

Afterwards set DB_SCHEMA=<target> in .env so the agent queries the views, and
re-run scripts/introspect_schema.py to regenerate the semantic layer.
"""

import argparse
from collections import defaultdict

from sqlalchemy import create_engine, text

from fsq_agent.config import settings

SOURCE_SCHEMA = "public"
DEFAULT_TARGET = "fsq_safe"

# Bookkeeping tables with no analytical value — no point giving them a view.
SKIP_TABLES = {"__EFMigrationsHistory"}


def fetch_columns(conn, schema: str) -> dict[str, list[str]]:
    rows = conn.execute(
        text(
            """
            SELECT c.table_name, c.column_name
            FROM information_schema.columns c
            JOIN information_schema.tables t
              ON t.table_schema = c.table_schema AND t.table_name = c.table_name
            WHERE c.table_schema = :schema AND t.table_type = 'BASE TABLE'
            ORDER BY c.table_name, c.ordinal_position
            """
        ),
        {"schema": schema},
    ).fetchall()

    tables: dict[str, list[str]] = defaultdict(list)
    for table, column in rows:
        tables[table].append(column)
    return tables


def render(tables: dict[str, list[str]], target: str) -> str:
    denied = settings.sensitive_column_set
    out = [
        "-- GENERATED by scripts/generate_safe_views.py — review before running.",
        f"-- Sensitive columns excluded: {', '.join(sorted(denied))}",
        "",
        f"CREATE SCHEMA IF NOT EXISTS {target};",
        "",
    ]

    skipped_whole_table: list[str] = []
    for table, columns in sorted(tables.items()):
        if table in SKIP_TABLES:
            continue
        safe = [c for c in columns if c.lower() not in denied]
        dropped = [c for c in columns if c.lower() in denied]

        if not safe:
            # Every column is sensitive: no view at all, so the table simply
            # does not resolve for the agent.
            skipped_whole_table.append(table)
            continue

        if dropped:
            out.append(f"-- {table}: withholding {', '.join(dropped)}")
        cols = ",\n         ".join(f'"{c}"' for c in safe)
        out += [
            f'CREATE OR REPLACE VIEW {target}."{table}" AS',
            f"  SELECT {cols}",
            f'  FROM {SOURCE_SCHEMA}."{table}";',
            "",
        ]

    if skipped_whole_table:
        out += [
            "-- No view emitted (every column is sensitive): "
            + ", ".join(skipped_whole_table),
            "",
        ]

    # The agent connects with search_path pinned to the target schema, so it
    # needs USAGE there and nothing on the source schema.
    out += [
        "-- Grant to whichever role the agent connects as, if that role is not",
        "-- the schema owner. Left commented: applying it is a deliberate step.",
        f"-- GRANT USAGE ON SCHEMA {target} TO <agent_role>;",
        f"-- GRANT SELECT ON ALL TABLES IN SCHEMA {target} TO <agent_role>;",
        "",
    ]
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-o", "--output", help="write DDL to this file")
    parser.add_argument(
        "--target-schema",
        default=settings.db_schema or DEFAULT_TARGET,
        help=f"schema to create the views in (default: {DEFAULT_TARGET})",
    )
    args = parser.parse_args()

    engine = create_engine(settings.database_url, connect_args={"connect_timeout": 30})
    with engine.connect() as conn:
        tables = fetch_columns(conn, SOURCE_SCHEMA)

    ddl = render(tables, args.target_schema)

    if args.output:
        with open(args.output, "w", encoding="utf-8") as fh:
            fh.write(ddl)
        views = ddl.count("CREATE OR REPLACE VIEW")
        print(f"wrote {args.output}  ({views} views over {len(tables)} tables)")
        print(f"Next: review it, run it, then set DB_SCHEMA={args.target_schema} in .env")
    else:
        print(ddl)


if __name__ == "__main__":
    main()
